version: '3.9'
services:
  db:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    networks:
        - backend

  api:
    build: ./api
    image: api
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M

    networks:
        - backend

networks:
    backend:
        driver: bridge